# Generated by Django 5.0.6 on 2024-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
